services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/pyfolio-deploy/
    environment:
      - POSTGRES_DB=pyfolio_db
      - POSTGRES_USER=pyfolio
      - POSTGRES_PASSWORD=87654321
    ports:
      - "8000:5432"

  equity_updater:
    build: ./equity_updater
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - ./equity_updater/:/usr/src/app/
    ports:
      - 8050:8050
    environment:
      - SQL_HOST=db
    env_file:
      - ./.env.dev
    depends_on:
      - db

  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8020:8000
    environment:
      - SQL_HOST=db
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
