# Generated by Django 3.2.6 on 2023-01-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('ticker', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('adj_open', models.FloatField()),
                ('adj_high', models.FloatField()),
                ('adj_low', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('adj_volume', models.FloatField()),
                ('intraperiod', models.BooleanField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_manager.security')),
            ],
        ),
    ]
